// Copyright (c) 2026 McSparrow. All rights reserved.
// McHarbor is licensed under the McHarbor License. See LICENSE for details.

package appstore

import (
	"strings"
	"testing"
)

func TestGenerateComposeRendersComposeOverride(t *testing.T) {
	app := AppTemplate{
		Slug:  "speech-to-phrase",
		Image: "rhasspy/wyoming-speech-to-phrase:latest",
		ComposeOverride: `# Generated by McHarbor App Store
services:
  {{serviceName}}:
    image: {{image}}
    container_name: {{containerName}}
    restart: unless-stopped
{{ports}}
{{volumes}}
{{environment}}
    command:
      - --hass-websocket-uri
      - {{env.HASS_WEBSOCKET_URI}}
      - --hass-token
      - {{env.HASS_TOKEN}}
`,
	}

	compose := generateCompose(
		app,
		"Speech To Phrase",
		[]PortMapping{{Host: 10300, Container: 10300, Protocol: "tcp"}},
		[]VolumeMount{{Host: "/opt/appdata/speech-to-phrase/models", Container: "/models"}},
		map[string]string{
			"HASS_WEBSOCKET_URI": "ws://homeassistant.local:8123/api/websocket",
			"HASS_TOKEN":         `token"withquote`,
		},
	)

	expectedParts := []string{
		"  speech-to-phrase:",
		"    image: rhasspy/wyoming-speech-to-phrase:latest",
		"    ports:\n      - \"10300:10300\"",
		"    volumes:\n      - \"/opt/appdata/speech-to-phrase/models:/models\"",
		"      - HASS_WEBSOCKET_URI=ws://homeassistant.local:8123/api/websocket",
		"      - \"ws://homeassistant.local:8123/api/websocket\"",
		"      - \"token\\\"withquote\"",
	}

	for _, part := range expectedParts {
		if !strings.Contains(compose, part) {
			t.Fatalf("expected compose to contain %q\ncompose:\n%s", part, compose)
		}
	}
}

func TestBundledCatalogComposeOverridesRender(t *testing.T) {
	catalog, err := loadBundledCatalog()
	if err != nil {
		t.Fatalf("loadBundledCatalog returned error: %v", err)
	}

	for _, app := range catalog.Apps {
		if app.ComposeOverride == "" {
			continue
		}

		envVars := make(map[string]string, len(app.EnvVars))
		for _, ev := range app.EnvVars {
			envVars[ev.Key] = ev.Default
		}

		compose := generateCompose(app, app.Slug, app.Ports, app.Volumes, envVars)
		if strings.Contains(compose, "{{") || strings.Contains(compose, "}}") {
			t.Fatalf("app %q rendered unresolved template placeholder:\n%s", app.Slug, compose)
		}
	}
}
