// Copyright (c) 2026 McSparrow. All rights reserved.
// McHarbor is licensed under the McHarbor License. See LICENSE for details.

package appstore

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// loadBundledCatalog parses the root apps catalog directory.
func loadBundledCatalog() (*CatalogFile, error) {
	appsDir, err := findBundledAppsDir()
	if err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(appsDir)
	if err != nil {
		return nil, fmt.Errorf("reading bundled apps directory: %w", err)
	}

	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		files = append(files, filepath.Join(appsDir, entry.Name()))
	}
	sort.Strings(files)

	catalog := &CatalogFile{Version: "1.0.0", Apps: make([]AppTemplate, 0, len(files))}
	for _, file := range files {
		app, err := loadAppTemplateFile(file)
		if err != nil {
			return nil, err
		}
		catalog.Apps = append(catalog.Apps, app)
	}

	return catalog, nil
}

func findBundledAppsDir() (string, error) {
	candidates := []string{
		"apps",
		"../../apps",
		"../../../apps",
		"../../../../apps",
	}

	if exe, err := os.Executable(); err == nil {
		candidates = append([]string{filepath.Join(filepath.Dir(exe), "apps")}, candidates...)
	}

	for _, candidate := range candidates {
		info, err := os.Stat(candidate)
		if err == nil && info.IsDir() {
			return candidate, nil
		}
	}

	return "", fmt.Errorf("bundled apps directory not found")
}

func loadAppTemplateFile(path string) (AppTemplate, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return AppTemplate{}, fmt.Errorf("reading bundled app %s: %w", filepath.Base(path), err)
	}

	var app AppTemplate
	if err := json.Unmarshal(data, &app); err != nil {
		return AppTemplate{}, fmt.Errorf("parsing bundled app %s: %w", filepath.Base(path), err)
	}
	if app.Slug == "" {
		return AppTemplate{}, fmt.Errorf("bundled app %s has empty slug", filepath.Base(path))
	}

	return app, nil
}

// generateCompose builds a docker-compose.yml string from an AppTemplate
// with optional user overrides for ports, volumes, env vars, and networking.
func generateCompose(app AppTemplate, name string, ports []PortMapping, volumes []VolumeMount, envVars map[string]string, netCfg *NetworkConfig) string {
	serviceName := sanitizeServiceName(name)
	if app.ComposeOverride != "" {
		return renderComposeOverride(app, serviceName, ports, volumes, envVars, netCfg)
	}

	var b strings.Builder
	b.WriteString("# Generated by McHarbor App Store\n")
	b.WriteString("services:\n")
	b.WriteString(fmt.Sprintf("  %s:\n", serviceName))
	b.WriteString(fmt.Sprintf("    image: %s\n", app.Image))
	b.WriteString(fmt.Sprintf("    container_name: %s\n", serviceName))
	b.WriteString("    restart: unless-stopped\n")

	// Ports
	if len(ports) > 0 {
		b.WriteString("    ports:\n")
		for _, p := range ports {
			proto := p.Protocol
			if proto == "" {
				proto = "tcp"
			}
			if proto == "tcp" {
				b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", p.Host, p.Container))
			} else {
				b.WriteString(fmt.Sprintf("      - \"%d:%d/%s\"\n", p.Host, p.Container, proto))
			}
		}
	}

	// Volumes
	if len(volumes) > 0 {
		b.WriteString("    volumes:\n")
		for _, v := range volumes {
			suffix := ""
			if v.ReadOnly {
				suffix = ":ro"
			}
			b.WriteString(fmt.Sprintf("      - %s:%s%s\n", v.Host, v.Container, suffix))
		}
	}

	// Environment variables
	if len(envVars) > 0 {
		b.WriteString("    environment:\n")
		for k, v := range envVars {
			b.WriteString(fmt.Sprintf("      - %s=%s\n", k, v))
		}
	}

	renderGeneratedNetwork(&b, netCfg)

	return b.String()
}

var composeEnvPlaceholder = regexp.MustCompile(`\{\{env\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)
var composeEnvListItemPlaceholder = regexp.MustCompile(`^(\s*-\s*)\{\{env\.([A-Za-z_][A-Za-z0-9_]*)\}\}(.*)$`)
var composeRawEnvPlaceholder = regexp.MustCompile(`\{\{envRaw\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)

func renderComposeOverride(app AppTemplate, serviceName string, ports []PortMapping, volumes []VolumeMount, envVars map[string]string, netCfg *NetworkConfig) string {
	compose := app.ComposeOverride
	appDataPath := "/opt/appdata/" + serviceName
	replacements := map[string]string{
		"{{serviceName}}":    serviceName,
		"{{containerName}}":  serviceName,
		"{{projectName}}":    serviceName,
		"{{appDataPath}}":    appDataPath,
		"{{image}}":          app.Image,
		"{{ports}}":          renderComposePorts(ports),
		"{{volumes}}":        renderComposeVolumes(volumes),
		"{{environment}}":    renderComposeEnvironment(envVars),
		"{{environmentMap}}": renderComposeEnvironmentMap(envVars),
		"{{networks}}":       renderComposeNetwork(netCfg),
		"{{networkMode}}":    renderComposeNetworkMode(netCfg),
	}
	for placeholder, value := range replacements {
		compose = strings.ReplaceAll(compose, placeholder, value)
	}
	compose = renderComposeEnvPlaceholders(compose, envVars)
	compose = composeRawEnvPlaceholder.ReplaceAllStringFunc(compose, func(match string) string {
		key := composeRawEnvPlaceholder.FindStringSubmatch(match)[1]
		return envVars[key]
	})
	if !strings.HasSuffix(compose, "\n") {
		compose += "\n"
	}
	return compose
}

func renderComposeEnvPlaceholders(compose string, envVars map[string]string) string {
	lines := strings.Split(compose, "\n")
	for i, line := range lines {
		if !strings.Contains(line, "{{env.") {
			continue
		}

		if match := composeEnvListItemPlaceholder.FindStringSubmatch(line); match != nil {
			lines[i] = match[1] + quoteYAMLString(envVars[match[2]]+match[3])
			continue
		}

		lines[i] = composeEnvPlaceholder.ReplaceAllStringFunc(line, func(match string) string {
			key := composeEnvPlaceholder.FindStringSubmatch(match)[1]
			return quoteYAMLString(envVars[key])
		})
	}
	return strings.Join(lines, "\n")
}

func renderGeneratedNetwork(b *strings.Builder, netCfg *NetworkConfig) {
	if netCfg == nil {
		return
	}

	mode := strings.TrimSpace(netCfg.Mode)
	switch mode {
	case "bridge", "host", "none":
		b.WriteString(fmt.Sprintf("    network_mode: %s\n", quoteYAMLString(mode)))
	case "existing":
		networkName := strings.TrimSpace(netCfg.Name)
		if networkName == "" {
			return
		}
		networkKey := sanitizeServiceName(networkName)
		if networkKey == "" {
			networkKey = "app-network"
		}
		b.WriteString("    networks:\n")
		if len(netCfg.Aliases) == 0 && strings.TrimSpace(netCfg.IPv4Address) == "" && strings.TrimSpace(netCfg.IPv6Address) == "" && strings.TrimSpace(netCfg.MACAddress) == "" {
			b.WriteString(fmt.Sprintf("      %s: {}\n", networkKey))
		} else {
			b.WriteString(fmt.Sprintf("      %s:\n", networkKey))
			if len(netCfg.Aliases) > 0 {
				b.WriteString("        aliases:\n")
				for _, alias := range netCfg.Aliases {
					alias = strings.TrimSpace(alias)
					if alias != "" {
						b.WriteString(fmt.Sprintf("          - %s\n", quoteYAMLString(alias)))
					}
				}
			}
			if value := strings.TrimSpace(netCfg.IPv4Address); value != "" {
				b.WriteString(fmt.Sprintf("        ipv4_address: %s\n", quoteYAMLString(value)))
			}
			if value := strings.TrimSpace(netCfg.IPv6Address); value != "" {
				b.WriteString(fmt.Sprintf("        ipv6_address: %s\n", quoteYAMLString(value)))
			}
			if value := strings.TrimSpace(netCfg.MACAddress); value != "" {
				b.WriteString(fmt.Sprintf("        mac_address: %s\n", quoteYAMLString(value)))
			}
		}
		b.WriteString("networks:\n")
		b.WriteString(fmt.Sprintf("  %s:\n", networkKey))
		b.WriteString("    external: true\n")
		b.WriteString(fmt.Sprintf("    name: %s\n", quoteYAMLString(networkName)))
	}
}

func renderComposeNetwork(netCfg *NetworkConfig) string {
	var b strings.Builder
	renderGeneratedNetwork(&b, netCfg)
	return strings.TrimRight(b.String(), "\n")
}

func renderComposeNetworkMode(netCfg *NetworkConfig) string {
	if netCfg == nil {
		return ""
	}
	mode := strings.TrimSpace(netCfg.Mode)
	if mode == "bridge" || mode == "host" || mode == "none" {
		return mode
	}
	return ""
}

func renderComposePorts(ports []PortMapping) string {
	if len(ports) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    ports:\n")
	for _, p := range ports {
		proto := p.Protocol
		if proto == "" {
			proto = "tcp"
		}
		value := fmt.Sprintf("%d:%d", p.Host, p.Container)
		if proto != "tcp" {
			value = fmt.Sprintf("%s/%s", value, proto)
		}
		b.WriteString(fmt.Sprintf("      - %s\n", quoteYAMLString(value)))
	}
	return strings.TrimRight(b.String(), "\n")
}

func renderComposeVolumes(volumes []VolumeMount) string {
	if len(volumes) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    volumes:\n")
	for _, v := range volumes {
		value := fmt.Sprintf("%s:%s", v.Host, v.Container)
		if v.ReadOnly {
			value += ":ro"
		}
		b.WriteString(fmt.Sprintf("      - %s\n", quoteYAMLString(value)))
	}
	return strings.TrimRight(b.String(), "\n")
}

func renderComposeEnvironment(envVars map[string]string) string {
	if len(envVars) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    environment:\n")
	for _, k := range sortedEnvKeys(envVars) {
		v := envVars[k]
		b.WriteString(fmt.Sprintf("      - %s=%s\n", k, v))
	}
	return strings.TrimRight(b.String(), "\n")
}

func renderComposeEnvironmentMap(envVars map[string]string) string {
	if len(envVars) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    environment:\n")
	for _, k := range sortedEnvKeys(envVars) {
		b.WriteString(fmt.Sprintf("      %s: %s\n", k, quoteYAMLString(envVars[k])))
	}
	return strings.TrimRight(b.String(), "\n")
}

func sortedEnvKeys(envVars map[string]string) []string {
	keys := make([]string, 0, len(envVars))
	for k := range envVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func quoteYAMLString(value string) string {
	b, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(b)
}

// mergeOverrides applies user-provided overrides to the app defaults.
// If the user provides ports/volumes, those replace defaults.
// Env vars are merged: user values override defaults, but defaults fill gaps.
func mergeOverrides(app AppTemplate, req InstallRequest) ([]PortMapping, []VolumeMount, map[string]string) {
	ports := app.Ports
	if len(req.Ports) > 0 {
		ports = req.Ports
	}

	volumes := app.Volumes
	if len(req.Volumes) > 0 {
		volumes = req.Volumes
	}

	envVars := make(map[string]string)
	// Start with app defaults
	for _, ev := range app.EnvVars {
		if ev.Default != "" {
			envVars[ev.Key] = ev.Default
		}
	}
	// Override with user-provided values
	for k, v := range req.EnvVars {
		envVars[k] = v
	}

	return ports, volumes, envVars
}

// sanitizeServiceName converts a name to a valid docker compose service name.
func sanitizeServiceName(name string) string {
	name = strings.ToLower(name)
	var b strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			b.WriteRune(c)
		} else if c == ' ' {
			b.WriteRune('-')
		}
	}
	result := b.String()
	result = strings.Trim(result, "-_")
	if result == "" {
		result = "app"
	}
	return result
}
