// Copyright (c) 2026 McSparrow. All rights reserved.
// McHarbor is licensed under the McHarbor License. See LICENSE for details.

package appstore

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

//go:embed data/catalog.json
var catalogJSON []byte

// loadBundledCatalog parses the embedded catalog JSON.
func loadBundledCatalog() (*CatalogFile, error) {
	var catalog CatalogFile
	if err := json.Unmarshal(catalogJSON, &catalog); err != nil {
		return nil, fmt.Errorf("parsing bundled catalog: %w", err)
	}
	return &catalog, nil
}

// generateCompose builds a docker-compose.yml string from an AppTemplate
// with optional user overrides for ports, volumes, and env vars.
func generateCompose(app AppTemplate, name string, ports []PortMapping, volumes []VolumeMount, envVars map[string]string) string {
	serviceName := sanitizeServiceName(name)
	if app.ComposeOverride != "" {
		return renderComposeOverride(app, serviceName, ports, volumes, envVars)
	}

	var b strings.Builder
	b.WriteString("# Generated by McHarbor App Store\n")
	b.WriteString("services:\n")
	b.WriteString(fmt.Sprintf("  %s:\n", serviceName))
	b.WriteString(fmt.Sprintf("    image: %s\n", app.Image))
	b.WriteString(fmt.Sprintf("    container_name: %s\n", serviceName))
	b.WriteString("    restart: unless-stopped\n")

	// Ports
	if len(ports) > 0 {
		b.WriteString("    ports:\n")
		for _, p := range ports {
			proto := p.Protocol
			if proto == "" {
				proto = "tcp"
			}
			if proto == "tcp" {
				b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", p.Host, p.Container))
			} else {
				b.WriteString(fmt.Sprintf("      - \"%d:%d/%s\"\n", p.Host, p.Container, proto))
			}
		}
	}

	// Volumes
	if len(volumes) > 0 {
		b.WriteString("    volumes:\n")
		for _, v := range volumes {
			suffix := ""
			if v.ReadOnly {
				suffix = ":ro"
			}
			b.WriteString(fmt.Sprintf("      - %s:%s%s\n", v.Host, v.Container, suffix))
		}
	}

	// Environment variables
	if len(envVars) > 0 {
		b.WriteString("    environment:\n")
		for k, v := range envVars {
			b.WriteString(fmt.Sprintf("      - %s=%s\n", k, v))
		}
	}

	return b.String()
}

var composeEnvPlaceholder = regexp.MustCompile(`\{\{env\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)

func renderComposeOverride(app AppTemplate, serviceName string, ports []PortMapping, volumes []VolumeMount, envVars map[string]string) string {
	compose := app.ComposeOverride
	replacements := map[string]string{
		"{{serviceName}}":   serviceName,
		"{{containerName}}": serviceName,
		"{{image}}":         app.Image,
		"{{ports}}":         renderComposePorts(ports),
		"{{volumes}}":       renderComposeVolumes(volumes),
		"{{environment}}":   renderComposeEnvironment(envVars),
	}
	for placeholder, value := range replacements {
		compose = strings.ReplaceAll(compose, placeholder, value)
	}
	compose = composeEnvPlaceholder.ReplaceAllStringFunc(compose, func(match string) string {
		key := composeEnvPlaceholder.FindStringSubmatch(match)[1]
		return quoteYAMLString(envVars[key])
	})
	if !strings.HasSuffix(compose, "\n") {
		compose += "\n"
	}
	return compose
}

func renderComposePorts(ports []PortMapping) string {
	if len(ports) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    ports:\n")
	for _, p := range ports {
		proto := p.Protocol
		if proto == "" {
			proto = "tcp"
		}
		value := fmt.Sprintf("%d:%d", p.Host, p.Container)
		if proto != "tcp" {
			value = fmt.Sprintf("%s/%s", value, proto)
		}
		b.WriteString(fmt.Sprintf("      - %s\n", quoteYAMLString(value)))
	}
	return strings.TrimRight(b.String(), "\n")
}

func renderComposeVolumes(volumes []VolumeMount) string {
	if len(volumes) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    volumes:\n")
	for _, v := range volumes {
		value := fmt.Sprintf("%s:%s", v.Host, v.Container)
		if v.ReadOnly {
			value += ":ro"
		}
		b.WriteString(fmt.Sprintf("      - %s\n", quoteYAMLString(value)))
	}
	return strings.TrimRight(b.String(), "\n")
}

func renderComposeEnvironment(envVars map[string]string) string {
	if len(envVars) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("    environment:\n")
	for k, v := range envVars {
		b.WriteString(fmt.Sprintf("      - %s=%s\n", k, v))
	}
	return strings.TrimRight(b.String(), "\n")
}

func quoteYAMLString(value string) string {
	b, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(b)
}

// mergeOverrides applies user-provided overrides to the app defaults.
// If the user provides ports/volumes, those replace defaults.
// Env vars are merged: user values override defaults, but defaults fill gaps.
func mergeOverrides(app AppTemplate, req InstallRequest) ([]PortMapping, []VolumeMount, map[string]string) {
	ports := app.Ports
	if len(req.Ports) > 0 {
		ports = req.Ports
	}

	volumes := app.Volumes
	if len(req.Volumes) > 0 {
		volumes = req.Volumes
	}

	envVars := make(map[string]string)
	// Start with app defaults
	for _, ev := range app.EnvVars {
		if ev.Default != "" {
			envVars[ev.Key] = ev.Default
		}
	}
	// Override with user-provided values
	for k, v := range req.EnvVars {
		envVars[k] = v
	}

	return ports, volumes, envVars
}

// sanitizeServiceName converts a name to a valid docker compose service name.
func sanitizeServiceName(name string) string {
	name = strings.ToLower(name)
	var b strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			b.WriteRune(c)
		} else if c == ' ' {
			b.WriteRune('-')
		}
	}
	result := b.String()
	result = strings.Trim(result, "-_")
	if result == "" {
		result = "app"
	}
	return result
}
