// Copyright (c) 2026 McSparrow. All rights reserved.
// McHarbor is licensed under the McHarbor License. See LICENSE for details.

package appstore

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

//go:embed data/catalog.json
var catalogJSON []byte

// loadBundledCatalog parses the embedded catalog JSON.
func loadBundledCatalog() (*CatalogFile, error) {
	var catalog CatalogFile
	if err := json.Unmarshal(catalogJSON, &catalog); err != nil {
		return nil, fmt.Errorf("parsing bundled catalog: %w", err)
	}
	return &catalog, nil
}

// generateCompose builds a docker-compose.yml string from an AppTemplate
// with optional user overrides for ports, volumes, and env vars.
func generateCompose(app AppTemplate, name string, ports []PortMapping, volumes []VolumeMount, envVars map[string]string) string {
	serviceName := sanitizeServiceName(name)

	var b strings.Builder
	b.WriteString("# Generated by McHarbor App Store\n")
	b.WriteString("services:\n")
	b.WriteString(fmt.Sprintf("  %s:\n", serviceName))
	b.WriteString(fmt.Sprintf("    image: %s\n", app.Image))
	b.WriteString(fmt.Sprintf("    container_name: %s\n", serviceName))
	b.WriteString("    restart: unless-stopped\n")

	// Ports
	if len(ports) > 0 {
		b.WriteString("    ports:\n")
		for _, p := range ports {
			proto := p.Protocol
			if proto == "" {
				proto = "tcp"
			}
			if proto == "tcp" {
				b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", p.Host, p.Container))
			} else {
				b.WriteString(fmt.Sprintf("      - \"%d:%d/%s\"\n", p.Host, p.Container, proto))
			}
		}
	}

	// Volumes
	if len(volumes) > 0 {
		b.WriteString("    volumes:\n")
		for _, v := range volumes {
			suffix := ""
			if v.ReadOnly {
				suffix = ":ro"
			}
			b.WriteString(fmt.Sprintf("      - %s:%s%s\n", v.Host, v.Container, suffix))
		}
	}

	// Environment variables
	if len(envVars) > 0 {
		b.WriteString("    environment:\n")
		for k, v := range envVars {
			b.WriteString(fmt.Sprintf("      - %s=%s\n", k, v))
		}
	}

	return b.String()
}

// mergeOverrides applies user-provided overrides to the app defaults.
// If the user provides ports/volumes, those replace defaults.
// Env vars are merged: user values override defaults, but defaults fill gaps.
func mergeOverrides(app AppTemplate, req InstallRequest) ([]PortMapping, []VolumeMount, map[string]string) {
	ports := app.Ports
	if len(req.Ports) > 0 {
		ports = req.Ports
	}

	volumes := app.Volumes
	if len(req.Volumes) > 0 {
		volumes = req.Volumes
	}

	envVars := make(map[string]string)
	// Start with app defaults
	for _, ev := range app.EnvVars {
		if ev.Default != "" {
			envVars[ev.Key] = ev.Default
		}
	}
	// Override with user-provided values
	for k, v := range req.EnvVars {
		envVars[k] = v
	}

	return ports, volumes, envVars
}

// sanitizeServiceName converts a name to a valid docker compose service name.
func sanitizeServiceName(name string) string {
	name = strings.ToLower(name)
	var b strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			b.WriteRune(c)
		} else if c == ' ' {
			b.WriteRune('-')
		}
	}
	result := b.String()
	result = strings.Trim(result, "-_")
	if result == "" {
		result = "app"
	}
	return result
}
