// Copyright (c) 2026 McSparrow. All rights reserved.
// McHarbor is licensed under the McHarbor License. See LICENSE for details.

import {
  IconWorld,
  IconDatabase,
  IconSearch,
  IconMessage,
  IconChartBar,
  IconMail,
  IconShield,
  IconGitBranch,
  IconDeviceFloppy,
  IconMovie,
  IconHome,
  IconCloud,
  IconCode,
  IconKey,
  IconRss,
} from '@tabler/icons-react';
import type { TablerIcon } from '@tabler/icons-react';

/** Maps Docker image base name (lowercase) to dashboard-icons SVG slug */
export const IMAGE_LOGO_MAP: Record<string, string> = {
  nginx: 'nginx',
  'nginx-proxy-manager': 'nginx-proxy-manager',
  apache: 'apache',
  httpd: 'apache',
  caddy: 'caddy',
  traefik: 'traefik',
  haproxy: 'haproxy',
  envoy: 'envoy',
  postgres: 'postgres',
  postgresql: 'postgres',
  mysql: 'mysql',
  mariadb: 'mariadb',
  mongo: 'mongodb',
  mongodb: 'mongodb',
  redis: 'redis',
  valkey: 'valkey',
  keydb: 'keydb',
  dragonfly: 'dragonflydb',
  memcached: 'memcached',
  influxdb: 'influxdb',
  cassandra: 'cassandra',
  couchdb: 'couchdb',
  neo4j: 'neo4j',
  cockroachdb: 'cockroachdb',
  cockroach: 'cockroachdb',
  timescaledb: 'timescaledb',
  clickhouse: 'clickhouse',
  elasticsearch: 'elasticsearch',
  opensearch: 'opensearch',
  kibana: 'kibana',
  logstash: 'logstash',
  meilisearch: 'meilisearch',
  typesense: 'typesense',
  solr: 'solr',
  rabbitmq: 'rabbitmq',
  kafka: 'apache-kafka',
  nats: 'nats',
  mosquitto: 'eclipse-mosquitto',
  emqx: 'emqx',
  grafana: 'grafana',
  prometheus: 'prometheus',
  loki: 'loki',
  jaeger: 'jaeger',
  'uptime-kuma': 'uptime-kuma',
  netdata: 'netdata',
  zabbix: 'zabbix',
  mailhog: 'mailhog',
  mailpit: 'mailpit',
  roundcube: 'roundcube',
  vault: 'vault',
  keycloak: 'keycloak',
  authelia: 'authelia',
  authentik: 'authentik',
  crowdsec: 'crowdsec',
  pihole: 'pi-hole',
  'pi-hole': 'pi-hole',
  adguard: 'adguard-home',
  'adguard-home': 'adguard-home',
  wireguard: 'wireguard',
  tailscale: 'tailscale',
  jenkins: 'jenkins',
  gitlab: 'gitlab',
  gitea: 'gitea',
  drone: 'drone',
  woodpecker: 'woodpecker-ci',
  sonarqube: 'sonarqube',
  harbor: 'harbor',
  registry: 'docker',
  minio: 'minio',
  duplicati: 'duplicati',
  syncthing: 'syncthing',
  restic: 'restic',
  plex: 'plex',
  jellyfin: 'jellyfin',
  emby: 'emby',
  sonarr: 'sonarr',
  radarr: 'radarr',
  lidarr: 'lidarr',
  prowlarr: 'prowlarr',
  bazarr: 'bazarr',
  overseerr: 'overseerr',
  tautulli: 'tautulli',
  homeassistant: 'home-assistant',
  'home-assistant': 'home-assistant',
  nodered: 'node-red',
  'node-red': 'node-red',
  zigbee2mqtt: 'zigbee2mqtt',
  nextcloud: 'nextcloud',
  owncloud: 'owncloud',
  seafile: 'seafile',
  filebrowser: 'filebrowser',
  cloudflare: 'cloudflare',
  'code-server': 'code-server',
  vaultwarden: 'vaultwarden',
  bitwarden: 'bitwarden',
  freshrss: 'freshrss',
  miniflux: 'miniflux',
  wordpress: 'wordpress',
  ghost: 'ghost',
  hugo: 'hugo',
  strapi: 'strapi',
  portainer: 'portainer',
  watchtower: 'watchtower',
  homepage: 'homepage',
  homarr: 'homarr',
  dashy: 'dashy',
  organizr: 'organizr',
  'unifi-controller': 'unifi',
  unifi: 'unifi',
  'paperless-ngx': 'paperless-ngx',
  paperless: 'paperless-ngx',
  immich: 'immich',
  photoprism: 'photoprism',
  bookstack: 'bookstack',
  wikijs: 'wiki-js',
  'wiki-js': 'wiki-js',
  n8n: 'n8n',
  actual: 'actual',
  'actual-server': 'actual',
  mealie: 'mealie',
  gotify: 'gotify',
  ntfy: 'ntfy',
  dozzle: 'dozzle',
  diun: 'diun',
  changedetection: 'changedetection-io',
  'changedetection.io': 'changedetection-io',
  linkwarden: 'linkwarden',
  linkding: 'linkding',
  grocy: 'grocy',
  tandoor: 'tandoor',
  'tandoor-recipes': 'tandoor',
  excalidraw: 'excalidraw',
  planka: 'planka',
  vikunja: 'vikunja',
};

/** Fallback: regex to Tabler icon for images without a logo */
export const IMAGE_ICON_MAP: [RegExp, TablerIcon][] = [
  [/nginx|apache|httpd|caddy|traefik|haproxy|envoy|litespeed/i, IconWorld],
  [/postgres|mysql|mariadb|mongo|redis|memcache|influx|cassandra|couchdb|neo4j|cockroach|timescale|clickhouse|sqlite|valkey|dragonfly|keydb/i, IconDatabase],
  [/elastic|opensearch|kibana|logstash|meilisearch|typesense|solr/i, IconSearch],
  [/rabbitmq|kafka|nats|mosquitto|emqx|pulsar|activemq|zeromq/i, IconMessage],
  [/grafana|prometheus|loki|tempo|jaeger|zipkin|datadog|zabbix|uptime-kuma|netdata/i, IconChartBar],
  [/mailhog|mailpit|mailtrap|postfix|dovecot|roundcube/i, IconMail],
  [/vault|keycloak|authelia|authentik|crowdsec|pihole|adguard|wireguard|tailscale/i, IconShield],
  [/jenkins|gitlab|gitea|drone|github|woodpecker|sonarqube|harbor|registry/i, IconGitBranch],
  [/minio|seaweedfs|ceph|restic|duplicati|syncthing/i, IconDeviceFloppy],
  [/plex|jellyfin|emby|sonarr|radarr|lidarr|prowlarr|bazarr|overseerr|tautulli/i, IconMovie],
  [/homeassistant|home-assistant|hass|nodered|node-red|zigbee2mqtt|mosquitto/i, IconHome],
  [/nextcloud|owncloud|seafile|filebrowser|cloudflare/i, IconCloud],
  [/node|deno|bun|python|php|ruby|golang|rust|java|dotnet|vscode|code-server/i, IconCode],
  [/bitwarden|vaultwarden|passbolt/i, IconKey],
  [/freshrss|miniflux|wordpress|ghost|hugo|strapi/i, IconRss],
];
